// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: api/proto/v1/entropy.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChecksumAlgo enumerates the supported checksum algorithms for batch integrity verification.
type ChecksumAlgo int32

const (
	ChecksumAlgo_CHECKSUM_ALGO_UNSPECIFIED ChecksumAlgo = 0
	ChecksumAlgo_CHECKSUM_SHA256           ChecksumAlgo = 1
)

// Enum value maps for ChecksumAlgo.
var (
	ChecksumAlgo_name = map[int32]string{
		0: "CHECKSUM_ALGO_UNSPECIFIED",
		1: "CHECKSUM_SHA256",
	}
	ChecksumAlgo_value = map[string]int32{
		"CHECKSUM_ALGO_UNSPECIFIED": 0,
		"CHECKSUM_SHA256":           1,
	}
)

func (x ChecksumAlgo) Enum() *ChecksumAlgo {
	p := new(ChecksumAlgo)
	*p = x
	return p
}

func (x ChecksumAlgo) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChecksumAlgo) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_entropy_proto_enumTypes[0].Descriptor()
}

func (ChecksumAlgo) Type() protoreflect.EnumType {
	return &file_api_proto_v1_entropy_proto_enumTypes[0]
}

func (x ChecksumAlgo) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChecksumAlgo.Descriptor instead.
func (ChecksumAlgo) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_entropy_proto_rawDescGZIP(), []int{0}
}

// SignatureAlgo enumerates the supported digital signature algorithms for batch authentication.
type SignatureAlgo int32

const (
	SignatureAlgo_SIGNATURE_ALGO_UNSPECIFIED SignatureAlgo = 0
	SignatureAlgo_SIGNATURE_ED25519          SignatureAlgo = 1
)

// Enum value maps for SignatureAlgo.
var (
	SignatureAlgo_name = map[int32]string{
		0: "SIGNATURE_ALGO_UNSPECIFIED",
		1: "SIGNATURE_ED25519",
	}
	SignatureAlgo_value = map[string]int32{
		"SIGNATURE_ALGO_UNSPECIFIED": 0,
		"SIGNATURE_ED25519":          1,
	}
)

func (x SignatureAlgo) Enum() *SignatureAlgo {
	p := new(SignatureAlgo)
	*p = x
	return p
}

func (x SignatureAlgo) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignatureAlgo) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_entropy_proto_enumTypes[1].Descriptor()
}

func (SignatureAlgo) Type() protoreflect.EnumType {
	return &file_api_proto_v1_entropy_proto_enumTypes[1]
}

func (x SignatureAlgo) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignatureAlgo.Descriptor instead.
func (SignatureAlgo) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_entropy_proto_rawDescGZIP(), []int{1}
}

// Compression enumerates the supported compression schemes applied to event payloads.
type Compression int32

const (
	Compression_COMPRESSION_NONE Compression = 0
	Compression_COMPRESSION_ZSTD Compression = 1
)

// Enum value maps for Compression.
var (
	Compression_name = map[int32]string{
		0: "COMPRESSION_NONE",
		1: "COMPRESSION_ZSTD",
	}
	Compression_value = map[string]int32{
		"COMPRESSION_NONE": 0,
		"COMPRESSION_ZSTD": 1,
	}
)

func (x Compression) Enum() *Compression {
	p := new(Compression)
	*p = x
	return p
}

func (x Compression) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Compression) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_entropy_proto_enumTypes[2].Descriptor()
}

func (Compression) Type() protoreflect.EnumType {
	return &file_api_proto_v1_entropy_proto_enumTypes[2]
}

func (x Compression) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Compression.Descriptor instead.
func (Compression) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_entropy_proto_rawDescGZIP(), []int{2}
}

// WhiteningStats captures output statistics from the entropy conditioning pipeline
// (Von Neumann extractor followed by a hash conditioner).
type WhiteningStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total number of raw input bits before conditioning.
	InputBits uint32 `protobuf:"varint,1,opt,name=input_bits,json=inputBits,proto3" json:"input_bits,omitempty"`
	// Total number of conditioned output bits after extraction.
	OutputBits uint32 `protobuf:"varint,2,opt,name=output_bits,json=outputBits,proto3" json:"output_bits,omitempty"`
	// Ratio of output_bits to input_bits, representing conditioning efficiency.
	ExtractionRate float64 `protobuf:"fixed64,3,opt,name=extraction_rate,json=extractionRate,proto3" json:"extraction_rate,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WhiteningStats) Reset() {
	*x = WhiteningStats{}
	mi := &file_api_proto_v1_entropy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhiteningStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhiteningStats) ProtoMessage() {}

func (x *WhiteningStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_entropy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhiteningStats.ProtoReflect.Descriptor instead.
func (*WhiteningStats) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_entropy_proto_rawDescGZIP(), []int{0}
}

func (x *WhiteningStats) GetInputBits() uint32 {
	if x != nil {
		return x.InputBits
	}
	return 0
}

func (x *WhiteningStats) GetOutputBits() uint32 {
	if x != nil {
		return x.OutputBits
	}
	return 0
}

func (x *WhiteningStats) GetExtractionRate() float64 {
	if x != nil {
		return x.ExtractionRate
	}
	return 0
}

// TestSummary holds edge-side quick-check results and optional lightweight
// NIST SP 800-90B health test statistics computed over a sliding window.
type TestSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// P-value from the monobit frequency test, if computed.
	FreqPvalue float64 `protobuf:"fixed64,1,opt,name=freq_pvalue,json=freqPvalue,proto3" json:"freq_pvalue,omitempty"`
	// P-value from the runs test, if computed.
	RunsPvalue float64 `protobuf:"fixed64,2,opt,name=runs_pvalue,json=runsPvalue,proto3" json:"runs_pvalue,omitempty"`
	// Repetition Count Test statistic.
	RctStat *float64 `protobuf:"fixed64,3,opt,name=rct_stat,json=rctStat,proto3,oneof" json:"rct_stat,omitempty"`
	// Adaptive Proportion Test statistic.
	AptStat *float64 `protobuf:"fixed64,4,opt,name=apt_stat,json=aptStat,proto3,oneof" json:"apt_stat,omitempty"`
	// Window size used for the Repetition Count Test.
	RctWindow *uint32 `protobuf:"varint,5,opt,name=rct_window,json=rctWindow,proto3,oneof" json:"rct_window,omitempty"`
	// Window size used for the Adaptive Proportion Test.
	AptWindow     *uint32 `protobuf:"varint,6,opt,name=apt_window,json=aptWindow,proto3,oneof" json:"apt_window,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestSummary) Reset() {
	*x = TestSummary{}
	mi := &file_api_proto_v1_entropy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestSummary) ProtoMessage() {}

func (x *TestSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_entropy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestSummary.ProtoReflect.Descriptor instead.
func (*TestSummary) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_entropy_proto_rawDescGZIP(), []int{1}
}

func (x *TestSummary) GetFreqPvalue() float64 {
	if x != nil {
		return x.FreqPvalue
	}
	return 0
}

func (x *TestSummary) GetRunsPvalue() float64 {
	if x != nil {
		return x.RunsPvalue
	}
	return 0
}

func (x *TestSummary) GetRctStat() float64 {
	if x != nil && x.RctStat != nil {
		return *x.RctStat
	}
	return 0
}

func (x *TestSummary) GetAptStat() float64 {
	if x != nil && x.AptStat != nil {
		return *x.AptStat
	}
	return 0
}

func (x *TestSummary) GetRctWindow() uint32 {
	if x != nil && x.RctWindow != nil {
		return *x.RctWindow
	}
	return 0
}

func (x *TestSummary) GetAptWindow() uint32 {
	if x != nil && x.AptWindow != nil {
		return *x.AptWindow
	}
	return 0
}

// KvMeta carries free-form key-value metadata labels attached to a batch or handshake.
type KvMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Arbitrary string labels, such as deployment location or sensor identifier.
	Labels        map[string]string `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KvMeta) Reset() {
	*x = KvMeta{}
	mi := &file_api_proto_v1_entropy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvMeta) ProtoMessage() {}

func (x *KvMeta) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_entropy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvMeta.ProtoReflect.Descriptor instead.
func (*KvMeta) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_entropy_proto_rawDescGZIP(), []int{2}
}

func (x *KvMeta) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// SubscriptionRequest initiates a server-to-client streaming subscription.
type SubscriptionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the subscribing client (e.g., "quarkus-validator-1").
	ClientId      string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionRequest) Reset() {
	*x = SubscriptionRequest{}
	mi := &file_api_proto_v1_entropy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionRequest) ProtoMessage() {}

func (x *SubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_entropy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionRequest.ProtoReflect.Descriptor instead.
func (*SubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_entropy_proto_rawDescGZIP(), []int{3}
}

func (x *SubscriptionRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// EntropyBatch represents a batch of TDC events collected at the edge gateway
// and transmitted to the cloud for analysis and storage.
type EntropyBatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ordered sequence of time-to-digital converter events in this batch.
	Events []*TDCEvent `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	// Edge-computed quality metrics summarizing this batch.
	Metrics *EdgeMetrics `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	// Timestamp when this batch was assembled, in microseconds since epoch.
	BatchTimestampUs uint64 `protobuf:"varint,3,opt,name=batch_timestamp_us,json=batchTimestampUs,proto3" json:"batch_timestamp_us,omitempty"`
	// Monotonically increasing sequence number for ordering and gap detection.
	BatchSequence uint32 `protobuf:"varint,4,opt,name=batch_sequence,json=batchSequence,proto3" json:"batch_sequence,omitempty"`
	// Identifier of the originating edge device (e.g., "raspi-07").
	SourceId string `protobuf:"bytes,5,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	// Start of the observation window, in microseconds since epoch.
	TStartUs uint64 `protobuf:"varint,6,opt,name=t_start_us,json=tStartUs,proto3" json:"t_start_us,omitempty"`
	// End of the observation window, in microseconds since epoch.
	TEndUs uint64 `protobuf:"varint,7,opt,name=t_end_us,json=tEndUs,proto3" json:"t_end_us,omitempty"`
	// Checksum computed over the raw (pre-compression) event payload.
	Checksum []byte `protobuf:"bytes,8,opt,name=checksum,proto3" json:"checksum,omitempty"`
	// Algorithm used to compute the checksum field.
	ChecksumAlgo ChecksumAlgo `protobuf:"varint,9,opt,name=checksum_algo,json=checksumAlgo,proto3,enum=entropy.ChecksumAlgo" json:"checksum_algo,omitempty"`
	// Digital signature over the concatenation of events, checksum, and header fields.
	Signature []byte `protobuf:"bytes,10,opt,name=signature,proto3,oneof" json:"signature,omitempty"`
	// Algorithm used to produce the signature field.
	SignatureAlgo *SignatureAlgo `protobuf:"varint,11,opt,name=signature_algo,json=signatureAlgo,proto3,enum=entropy.SignatureAlgo,oneof" json:"signature_algo,omitempty"`
	// Compression scheme applied to the events payload; COMPRESSION_NONE if uncompressed.
	Compression Compression `protobuf:"varint,12,opt,name=compression,proto3,enum=entropy.Compression" json:"compression,omitempty"`
	// Number of events lost or discarded at the edge before batching.
	DroppedEvents uint32 `protobuf:"varint,13,opt,name=dropped_events,json=droppedEvents,proto3" json:"dropped_events,omitempty"`
	// Statistics from the entropy conditioning (whitening) stage, if applied.
	Whitening *WhiteningStats `protobuf:"bytes,14,opt,name=whitening,proto3,oneof" json:"whitening,omitempty"`
	// Detailed edge-side health test results for this batch.
	Tests *TestSummary `protobuf:"bytes,15,opt,name=tests,proto3,oneof" json:"tests,omitempty"`
	// Free-form metadata labels (e.g., site, serial number).
	Meta          *KvMeta `protobuf:"bytes,16,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntropyBatch) Reset() {
	*x = EntropyBatch{}
	mi := &file_api_proto_v1_entropy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntropyBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntropyBatch) ProtoMessage() {}

func (x *EntropyBatch) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_entropy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntropyBatch.ProtoReflect.Descriptor instead.
func (*EntropyBatch) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_entropy_proto_rawDescGZIP(), []int{4}
}

func (x *EntropyBatch) GetEvents() []*TDCEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *EntropyBatch) GetMetrics() *EdgeMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *EntropyBatch) GetBatchTimestampUs() uint64 {
	if x != nil {
		return x.BatchTimestampUs
	}
	return 0
}

func (x *EntropyBatch) GetBatchSequence() uint32 {
	if x != nil {
		return x.BatchSequence
	}
	return 0
}

func (x *EntropyBatch) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *EntropyBatch) GetTStartUs() uint64 {
	if x != nil {
		return x.TStartUs
	}
	return 0
}

func (x *EntropyBatch) GetTEndUs() uint64 {
	if x != nil {
		return x.TEndUs
	}
	return 0
}

func (x *EntropyBatch) GetChecksum() []byte {
	if x != nil {
		return x.Checksum
	}
	return nil
}

func (x *EntropyBatch) GetChecksumAlgo() ChecksumAlgo {
	if x != nil {
		return x.ChecksumAlgo
	}
	return ChecksumAlgo_CHECKSUM_ALGO_UNSPECIFIED
}

func (x *EntropyBatch) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *EntropyBatch) GetSignatureAlgo() SignatureAlgo {
	if x != nil && x.SignatureAlgo != nil {
		return *x.SignatureAlgo
	}
	return SignatureAlgo_SIGNATURE_ALGO_UNSPECIFIED
}

func (x *EntropyBatch) GetCompression() Compression {
	if x != nil {
		return x.Compression
	}
	return Compression_COMPRESSION_NONE
}

func (x *EntropyBatch) GetDroppedEvents() uint32 {
	if x != nil {
		return x.DroppedEvents
	}
	return 0
}

func (x *EntropyBatch) GetWhitening() *WhiteningStats {
	if x != nil {
		return x.Whitening
	}
	return nil
}

func (x *EntropyBatch) GetTests() *TestSummary {
	if x != nil {
		return x.Tests
	}
	return nil
}

func (x *EntropyBatch) GetMeta() *KvMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

// TDCEvent represents a single time-to-digital converter measurement
// captured by a Raspberry Pi edge device.
type TDCEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raspberry Pi system clock timestamp in microseconds since epoch.
	RpiTimestampUs uint64 `protobuf:"varint,1,opt,name=rpi_timestamp_us,json=rpiTimestampUs,proto3" json:"rpi_timestamp_us,omitempty"`
	// TDC hardware timestamp in picoseconds, representing the precise detection time.
	TdcTimestampPs uint64 `protobuf:"varint,2,opt,name=tdc_timestamp_ps,json=tdcTimestampPs,proto3" json:"tdc_timestamp_ps,omitempty"`
	// TDC input channel number (typically 0 for single-channel configurations).
	Channel uint32 `protobuf:"varint,3,opt,name=channel,proto3" json:"channel,omitempty"`
	// Time difference from the previous event in picoseconds, if available.
	DeltaPs *int64 `protobuf:"varint,4,opt,name=delta_ps,json=deltaPs,proto3,oneof" json:"delta_ps,omitempty"`
	// Bit flags indicating hardware conditions (e.g., saturation, overrun).
	Flags         *uint32 `protobuf:"varint,5,opt,name=flags,proto3,oneof" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TDCEvent) Reset() {
	*x = TDCEvent{}
	mi := &file_api_proto_v1_entropy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TDCEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TDCEvent) ProtoMessage() {}

func (x *TDCEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_entropy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TDCEvent.ProtoReflect.Descriptor instead.
func (*TDCEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_entropy_proto_rawDescGZIP(), []int{5}
}

func (x *TDCEvent) GetRpiTimestampUs() uint64 {
	if x != nil {
		return x.RpiTimestampUs
	}
	return 0
}

func (x *TDCEvent) GetTdcTimestampPs() uint64 {
	if x != nil {
		return x.TdcTimestampPs
	}
	return 0
}

func (x *TDCEvent) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *TDCEvent) GetDeltaPs() int64 {
	if x != nil && x.DeltaPs != nil {
		return *x.DeltaPs
	}
	return 0
}

func (x *TDCEvent) GetFlags() uint32 {
	if x != nil && x.Flags != nil {
		return *x.Flags
	}
	return 0
}

// EdgeMetrics contains quality and performance metrics computed at the edge
// gateway for a given entropy batch.
type EdgeMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Shannon entropy estimate (bits per symbol) computed over the batch.
	QuickShannonEntropy float64 `protobuf:"fixed64,1,opt,name=quick_shannon_entropy,json=quickShannonEntropy,proto3" json:"quick_shannon_entropy,omitempty"`
	// Whether the monobit frequency test passed at the edge.
	FrequencyTestPassed bool `protobuf:"varint,2,opt,name=frequency_test_passed,json=frequencyTestPassed,proto3" json:"frequency_test_passed,omitempty"`
	// Whether the runs test passed at the edge.
	RunsTestPassed bool `protobuf:"varint,3,opt,name=runs_test_passed,json=runsTestPassed,proto3" json:"runs_test_passed,omitempty"`
	// Current size of the local entropy pool in bytes.
	PoolSize uint32 `protobuf:"varint,4,opt,name=pool_size,json=poolSize,proto3" json:"pool_size,omitempty"`
	// Time spent processing this batch at the edge, in microseconds.
	ProcessingLatencyUs uint64 `protobuf:"varint,5,opt,name=processing_latency_us,json=processingLatencyUs,proto3" json:"processing_latency_us,omitempty"`
	// Estimated bit bias in parts per million, if measured.
	BiasPpm *float64 `protobuf:"fixed64,6,opt,name=bias_ppm,json=biasPpm,proto3,oneof" json:"bias_ppm,omitempty"`
	// Whether the lightweight Repetition Count Test passed at the edge.
	RctPassed *bool `protobuf:"varint,7,opt,name=rct_passed,json=rctPassed,proto3,oneof" json:"rct_passed,omitempty"`
	// Whether the lightweight Adaptive Proportion Test passed at the edge.
	AptPassed     *bool `protobuf:"varint,8,opt,name=apt_passed,json=aptPassed,proto3,oneof" json:"apt_passed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeMetrics) Reset() {
	*x = EdgeMetrics{}
	mi := &file_api_proto_v1_entropy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeMetrics) ProtoMessage() {}

func (x *EdgeMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_entropy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeMetrics.ProtoReflect.Descriptor instead.
func (*EdgeMetrics) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_entropy_proto_rawDescGZIP(), []int{6}
}

func (x *EdgeMetrics) GetQuickShannonEntropy() float64 {
	if x != nil {
		return x.QuickShannonEntropy
	}
	return 0
}

func (x *EdgeMetrics) GetFrequencyTestPassed() bool {
	if x != nil {
		return x.FrequencyTestPassed
	}
	return false
}

func (x *EdgeMetrics) GetRunsTestPassed() bool {
	if x != nil {
		return x.RunsTestPassed
	}
	return false
}

func (x *EdgeMetrics) GetPoolSize() uint32 {
	if x != nil {
		return x.PoolSize
	}
	return 0
}

func (x *EdgeMetrics) GetProcessingLatencyUs() uint64 {
	if x != nil {
		return x.ProcessingLatencyUs
	}
	return 0
}

func (x *EdgeMetrics) GetBiasPpm() float64 {
	if x != nil && x.BiasPpm != nil {
		return *x.BiasPpm
	}
	return 0
}

func (x *EdgeMetrics) GetRctPassed() bool {
	if x != nil && x.RctPassed != nil {
		return *x.RctPassed
	}
	return false
}

func (x *EdgeMetrics) GetAptPassed() bool {
	if x != nil && x.AptPassed != nil {
		return *x.AptPassed
	}
	return false
}

// Ack is the cloud-to-edge acknowledgment for a received entropy batch.
type Ack struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the batch was accepted and persisted successfully.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Sequence number of the acknowledged batch.
	ReceivedSequence uint32 `protobuf:"varint,2,opt,name=received_sequence,json=receivedSequence,proto3" json:"received_sequence,omitempty"`
	// Human-readable status or error description.
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Sequence numbers of batches not yet received, for gap detection and retransmission.
	MissingSequences []uint32 `protobuf:"varint,4,rep,packed,name=missing_sequences,json=missingSequences,proto3" json:"missing_sequences,omitempty"`
	// Server-side receive timestamp in microseconds since epoch.
	ReceivedAtUs *uint64 `protobuf:"varint,5,opt,name=received_at_us,json=receivedAtUs,proto3,oneof" json:"received_at_us,omitempty"`
	// When true, indicates the edge should reduce its transmission rate.
	Backpressure *bool `protobuf:"varint,6,opt,name=backpressure,proto3,oneof" json:"backpressure,omitempty"`
	// Reason for the backpressure signal, if applicable.
	BackpressureReason *string `protobuf:"bytes,7,opt,name=backpressure_reason,json=backpressureReason,proto3,oneof" json:"backpressure_reason,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_api_proto_v1_entropy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_entropy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_entropy_proto_rawDescGZIP(), []int{7}
}

func (x *Ack) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Ack) GetReceivedSequence() uint32 {
	if x != nil {
		return x.ReceivedSequence
	}
	return 0
}

func (x *Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Ack) GetMissingSequences() []uint32 {
	if x != nil {
		return x.MissingSequences
	}
	return nil
}

func (x *Ack) GetReceivedAtUs() uint64 {
	if x != nil && x.ReceivedAtUs != nil {
		return *x.ReceivedAtUs
	}
	return 0
}

func (x *Ack) GetBackpressure() bool {
	if x != nil && x.Backpressure != nil {
		return *x.Backpressure
	}
	return false
}

func (x *Ack) GetBackpressureReason() string {
	if x != nil && x.BackpressureReason != nil {
		return *x.BackpressureReason
	}
	return ""
}

// ConfigUpdate carries tunable runtime parameters pushed from the cloud to the edge.
// Full NIST SP 800-90B validation is performed in the cloud; these thresholds
// control lightweight edge-side checks and batching behavior.
type ConfigUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Desired number of events per batch.
	TargetBatchSize *uint32 `protobuf:"varint,1,opt,name=target_batch_size,json=targetBatchSize,proto3,oneof" json:"target_batch_size,omitempty"`
	// Maximum requests per second for the entropy bytes API endpoint.
	MaxRps *uint32 `protobuf:"varint,2,opt,name=max_rps,json=maxRps,proto3,oneof" json:"max_rps,omitempty"`
	// Window size for the Repetition Count Test at the edge.
	RctWindow *uint32 `protobuf:"varint,3,opt,name=rct_window,json=rctWindow,proto3,oneof" json:"rct_window,omitempty"`
	// Window size for the Adaptive Proportion Test at the edge.
	AptWindow *uint32 `protobuf:"varint,4,opt,name=apt_window,json=aptWindow,proto3,oneof" json:"apt_window,omitempty"`
	// Bias warning threshold in parts per million.
	FreqWarnPpm *float64 `protobuf:"fixed64,5,opt,name=freq_warn_ppm,json=freqWarnPpm,proto3,oneof" json:"freq_warn_ppm,omitempty"`
	// Whether to enable Zstandard compression for event payloads.
	EnableZstd    *bool `protobuf:"varint,6,opt,name=enable_zstd,json=enableZstd,proto3,oneof" json:"enable_zstd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigUpdate) Reset() {
	*x = ConfigUpdate{}
	mi := &file_api_proto_v1_entropy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigUpdate) ProtoMessage() {}

func (x *ConfigUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_entropy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigUpdate.ProtoReflect.Descriptor instead.
func (*ConfigUpdate) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_entropy_proto_rawDescGZIP(), []int{8}
}

func (x *ConfigUpdate) GetTargetBatchSize() uint32 {
	if x != nil && x.TargetBatchSize != nil {
		return *x.TargetBatchSize
	}
	return 0
}

func (x *ConfigUpdate) GetMaxRps() uint32 {
	if x != nil && x.MaxRps != nil {
		return *x.MaxRps
	}
	return 0
}

func (x *ConfigUpdate) GetRctWindow() uint32 {
	if x != nil && x.RctWindow != nil {
		return *x.RctWindow
	}
	return 0
}

func (x *ConfigUpdate) GetAptWindow() uint32 {
	if x != nil && x.AptWindow != nil {
		return *x.AptWindow
	}
	return 0
}

func (x *ConfigUpdate) GetFreqWarnPpm() float64 {
	if x != nil && x.FreqWarnPpm != nil {
		return *x.FreqWarnPpm
	}
	return 0
}

func (x *ConfigUpdate) GetEnableZstd() bool {
	if x != nil && x.EnableZstd != nil {
		return *x.EnableZstd
	}
	return false
}

// HealthReport conveys the operational status of the edge gateway to the cloud.
type HealthReport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the gateway is ready to serve entropy (mirrors readiness probe).
	Ready bool `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	// Whether the gateway is operating normally (mirrors liveness probe).
	Healthy bool `protobuf:"varint,2,opt,name=healthy,proto3" json:"healthy,omitempty"`
	// Current size of the local entropy pool in bytes.
	PoolSize uint32 `protobuf:"varint,3,opt,name=pool_size,json=poolSize,proto3" json:"pool_size,omitempty"`
	// Round-trip latency of the most recent acknowledgment, in microseconds.
	LastAckLatencyUs uint64 `protobuf:"varint,4,opt,name=last_ack_latency_us,json=lastAckLatencyUs,proto3" json:"last_ack_latency_us,omitempty"`
	// Free-text summary of recent operational events (errors, reconnections).
	Summary       string `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthReport) Reset() {
	*x = HealthReport{}
	mi := &file_api_proto_v1_entropy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthReport) ProtoMessage() {}

func (x *HealthReport) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_entropy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthReport.ProtoReflect.Descriptor instead.
func (*HealthReport) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_entropy_proto_rawDescGZIP(), []int{9}
}

func (x *HealthReport) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *HealthReport) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthReport) GetPoolSize() uint32 {
	if x != nil {
		return x.PoolSize
	}
	return 0
}

func (x *HealthReport) GetLastAckLatencyUs() uint64 {
	if x != nil {
		return x.LastAckLatencyUs
	}
	return 0
}

func (x *HealthReport) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

// Nack signals a rejected or unprocessable batch from the cloud to the edge.
type Nack struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sequence number the cloud expected but did not receive correctly.
	ExpectedSequence uint32 `protobuf:"varint,1,opt,name=expected_sequence,json=expectedSequence,proto3" json:"expected_sequence,omitempty"`
	// Reason for the rejection (e.g., "checksum mismatch", "schema error").
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nack) Reset() {
	*x = Nack{}
	mi := &file_api_proto_v1_entropy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nack) ProtoMessage() {}

func (x *Nack) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_entropy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nack.ProtoReflect.Descriptor instead.
func (*Nack) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_entropy_proto_rawDescGZIP(), []int{10}
}

func (x *Nack) GetExpectedSequence() uint32 {
	if x != nil {
		return x.ExpectedSequence
	}
	return 0
}

func (x *Nack) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Ping is a keepalive probe sent on the control stream.
type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TsUs          uint64                 `protobuf:"varint,1,opt,name=ts_us,json=tsUs,proto3" json:"ts_us,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_api_proto_v1_entropy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_entropy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_entropy_proto_rawDescGZIP(), []int{11}
}

func (x *Ping) GetTsUs() uint64 {
	if x != nil {
		return x.TsUs
	}
	return 0
}

// Pong is the response to a Ping keepalive probe.
type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TsUs          uint64                 `protobuf:"varint,1,opt,name=ts_us,json=tsUs,proto3" json:"ts_us,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_api_proto_v1_entropy_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_entropy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_entropy_proto_rawDescGZIP(), []int{12}
}

func (x *Pong) GetTsUs() uint64 {
	if x != nil {
		return x.TsUs
	}
	return 0
}

// Hello is the initial handshake message sent by the edge gateway
// when establishing a control stream connection.
type Hello struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of the originating edge device.
	SourceId string `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	// Software version of the edge gateway.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Optional metadata labels for the connecting device.
	Meta          *KvMeta `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_api_proto_v1_entropy_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_entropy_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_entropy_proto_rawDescGZIP(), []int{13}
}

func (x *Hello) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Hello) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Hello) GetMeta() *KvMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

// ControlMessage is a union wrapper for all control plane message types
// exchanged over the bidirectional Control stream.
type ControlMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ControlMessage_Hello
	//	*ControlMessage_ConfigUpdate
	//	*ControlMessage_HealthReport
	//	*ControlMessage_Ping
	//	*ControlMessage_Pong
	Payload       isControlMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_api_proto_v1_entropy_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_entropy_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_entropy_proto_rawDescGZIP(), []int{14}
}

func (x *ControlMessage) GetPayload() isControlMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ControlMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ControlMessage) GetConfigUpdate() *ConfigUpdate {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_ConfigUpdate); ok {
			return x.ConfigUpdate
		}
	}
	return nil
}

func (x *ControlMessage) GetHealthReport() *HealthReport {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_HealthReport); ok {
			return x.HealthReport
		}
	}
	return nil
}

func (x *ControlMessage) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *ControlMessage) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

type isControlMessage_Payload interface {
	isControlMessage_Payload()
}

type ControlMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type ControlMessage_ConfigUpdate struct {
	ConfigUpdate *ConfigUpdate `protobuf:"bytes,2,opt,name=config_update,json=configUpdate,proto3,oneof"`
}

type ControlMessage_HealthReport struct {
	HealthReport *HealthReport `protobuf:"bytes,3,opt,name=health_report,json=healthReport,proto3,oneof"`
}

type ControlMessage_Ping struct {
	Ping *Ping `protobuf:"bytes,4,opt,name=ping,proto3,oneof"`
}

type ControlMessage_Pong struct {
	Pong *Pong `protobuf:"bytes,5,opt,name=pong,proto3,oneof"`
}

func (*ControlMessage_Hello) isControlMessage_Payload() {}

func (*ControlMessage_ConfigUpdate) isControlMessage_Payload() {}

func (*ControlMessage_HealthReport) isControlMessage_Payload() {}

func (*ControlMessage_Ping) isControlMessage_Payload() {}

func (*ControlMessage_Pong) isControlMessage_Payload() {}

var File_api_proto_v1_entropy_proto protoreflect.FileDescriptor

const file_api_proto_v1_entropy_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/proto/v1/entropy.proto\x12\aentropy\"y\n" +
	"\x0eWhiteningStats\x12\x1d\n" +
	"\n" +
	"input_bits\x18\x01 \x01(\rR\tinputBits\x12\x1f\n" +
	"\voutput_bits\x18\x02 \x01(\rR\n" +
	"outputBits\x12'\n" +
	"\x0fextraction_rate\x18\x03 \x01(\x01R\x0eextractionRate\"\x8f\x02\n" +
	"\vTestSummary\x12\x1f\n" +
	"\vfreq_pvalue\x18\x01 \x01(\x01R\n" +
	"freqPvalue\x12\x1f\n" +
	"\vruns_pvalue\x18\x02 \x01(\x01R\n" +
	"runsPvalue\x12\x1e\n" +
	"\brct_stat\x18\x03 \x01(\x01H\x00R\arctStat\x88\x01\x01\x12\x1e\n" +
	"\bapt_stat\x18\x04 \x01(\x01H\x01R\aaptStat\x88\x01\x01\x12\"\n" +
	"\n" +
	"rct_window\x18\x05 \x01(\rH\x02R\trctWindow\x88\x01\x01\x12\"\n" +
	"\n" +
	"apt_window\x18\x06 \x01(\rH\x03R\taptWindow\x88\x01\x01B\v\n" +
	"\t_rct_statB\v\n" +
	"\t_apt_statB\r\n" +
	"\v_rct_windowB\r\n" +
	"\v_apt_window\"x\n" +
	"\x06KvMeta\x123\n" +
	"\x06labels\x18\x01 \x03(\v2\x1b.entropy.KvMeta.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"2\n" +
	"\x13SubscriptionRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"\xfc\x05\n" +
	"\fEntropyBatch\x12)\n" +
	"\x06events\x18\x01 \x03(\v2\x11.entropy.TDCEventR\x06events\x12.\n" +
	"\ametrics\x18\x02 \x01(\v2\x14.entropy.EdgeMetricsR\ametrics\x12,\n" +
	"\x12batch_timestamp_us\x18\x03 \x01(\x04R\x10batchTimestampUs\x12%\n" +
	"\x0ebatch_sequence\x18\x04 \x01(\rR\rbatchSequence\x12\x1b\n" +
	"\tsource_id\x18\x05 \x01(\tR\bsourceId\x12\x1c\n" +
	"\n" +
	"t_start_us\x18\x06 \x01(\x04R\btStartUs\x12\x18\n" +
	"\bt_end_us\x18\a \x01(\x04R\x06tEndUs\x12\x1a\n" +
	"\bchecksum\x18\b \x01(\fR\bchecksum\x12:\n" +
	"\rchecksum_algo\x18\t \x01(\x0e2\x15.entropy.ChecksumAlgoR\fchecksumAlgo\x12!\n" +
	"\tsignature\x18\n" +
	" \x01(\fH\x00R\tsignature\x88\x01\x01\x12B\n" +
	"\x0esignature_algo\x18\v \x01(\x0e2\x16.entropy.SignatureAlgoH\x01R\rsignatureAlgo\x88\x01\x01\x126\n" +
	"\vcompression\x18\f \x01(\x0e2\x14.entropy.CompressionR\vcompression\x12%\n" +
	"\x0edropped_events\x18\r \x01(\rR\rdroppedEvents\x12:\n" +
	"\twhitening\x18\x0e \x01(\v2\x17.entropy.WhiteningStatsH\x02R\twhitening\x88\x01\x01\x12/\n" +
	"\x05tests\x18\x0f \x01(\v2\x14.entropy.TestSummaryH\x03R\x05tests\x88\x01\x01\x12#\n" +
	"\x04meta\x18\x10 \x01(\v2\x0f.entropy.KvMetaR\x04metaB\f\n" +
	"\n" +
	"_signatureB\x11\n" +
	"\x0f_signature_algoB\f\n" +
	"\n" +
	"_whiteningB\b\n" +
	"\x06_tests\"\xca\x01\n" +
	"\bTDCEvent\x12(\n" +
	"\x10rpi_timestamp_us\x18\x01 \x01(\x04R\x0erpiTimestampUs\x12(\n" +
	"\x10tdc_timestamp_ps\x18\x02 \x01(\x04R\x0etdcTimestampPs\x12\x18\n" +
	"\achannel\x18\x03 \x01(\rR\achannel\x12\x1e\n" +
	"\bdelta_ps\x18\x04 \x01(\x03H\x00R\adeltaPs\x88\x01\x01\x12\x19\n" +
	"\x05flags\x18\x05 \x01(\rH\x01R\x05flags\x88\x01\x01B\v\n" +
	"\t_delta_psB\b\n" +
	"\x06_flags\"\x83\x03\n" +
	"\vEdgeMetrics\x122\n" +
	"\x15quick_shannon_entropy\x18\x01 \x01(\x01R\x13quickShannonEntropy\x122\n" +
	"\x15frequency_test_passed\x18\x02 \x01(\bR\x13frequencyTestPassed\x12(\n" +
	"\x10runs_test_passed\x18\x03 \x01(\bR\x0erunsTestPassed\x12\x1b\n" +
	"\tpool_size\x18\x04 \x01(\rR\bpoolSize\x122\n" +
	"\x15processing_latency_us\x18\x05 \x01(\x04R\x13processingLatencyUs\x12\x1e\n" +
	"\bbias_ppm\x18\x06 \x01(\x01H\x00R\abiasPpm\x88\x01\x01\x12\"\n" +
	"\n" +
	"rct_passed\x18\a \x01(\bH\x01R\trctPassed\x88\x01\x01\x12\"\n" +
	"\n" +
	"apt_passed\x18\b \x01(\bH\x02R\taptPassed\x88\x01\x01B\v\n" +
	"\t_bias_ppmB\r\n" +
	"\v_rct_passedB\r\n" +
	"\v_apt_passed\"\xd9\x02\n" +
	"\x03Ack\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12+\n" +
	"\x11received_sequence\x18\x02 \x01(\rR\x10receivedSequence\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12+\n" +
	"\x11missing_sequences\x18\x04 \x03(\rR\x10missingSequences\x12)\n" +
	"\x0ereceived_at_us\x18\x05 \x01(\x04H\x00R\freceivedAtUs\x88\x01\x01\x12'\n" +
	"\fbackpressure\x18\x06 \x01(\bH\x01R\fbackpressure\x88\x01\x01\x124\n" +
	"\x13backpressure_reason\x18\a \x01(\tH\x02R\x12backpressureReason\x88\x01\x01B\x11\n" +
	"\x0f_received_at_usB\x0f\n" +
	"\r_backpressureB\x16\n" +
	"\x14_backpressure_reason\"\xd6\x02\n" +
	"\fConfigUpdate\x12/\n" +
	"\x11target_batch_size\x18\x01 \x01(\rH\x00R\x0ftargetBatchSize\x88\x01\x01\x12\x1c\n" +
	"\amax_rps\x18\x02 \x01(\rH\x01R\x06maxRps\x88\x01\x01\x12\"\n" +
	"\n" +
	"rct_window\x18\x03 \x01(\rH\x02R\trctWindow\x88\x01\x01\x12\"\n" +
	"\n" +
	"apt_window\x18\x04 \x01(\rH\x03R\taptWindow\x88\x01\x01\x12'\n" +
	"\rfreq_warn_ppm\x18\x05 \x01(\x01H\x04R\vfreqWarnPpm\x88\x01\x01\x12$\n" +
	"\venable_zstd\x18\x06 \x01(\bH\x05R\n" +
	"enableZstd\x88\x01\x01B\x14\n" +
	"\x12_target_batch_sizeB\n" +
	"\n" +
	"\b_max_rpsB\r\n" +
	"\v_rct_windowB\r\n" +
	"\v_apt_windowB\x10\n" +
	"\x0e_freq_warn_ppmB\x0e\n" +
	"\f_enable_zstd\"\xa4\x01\n" +
	"\fHealthReport\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x18\n" +
	"\ahealthy\x18\x02 \x01(\bR\ahealthy\x12\x1b\n" +
	"\tpool_size\x18\x03 \x01(\rR\bpoolSize\x12-\n" +
	"\x13last_ack_latency_us\x18\x04 \x01(\x04R\x10lastAckLatencyUs\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\"K\n" +
	"\x04Nack\x12+\n" +
	"\x11expected_sequence\x18\x01 \x01(\rR\x10expectedSequence\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x1b\n" +
	"\x04Ping\x12\x13\n" +
	"\x05ts_us\x18\x01 \x01(\x04R\x04tsUs\"\x1b\n" +
	"\x04Pong\x12\x13\n" +
	"\x05ts_us\x18\x01 \x01(\x04R\x04tsUs\"c\n" +
	"\x05Hello\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12#\n" +
	"\x04meta\x18\x03 \x01(\v2\x0f.entropy.KvMetaR\x04meta\"\x89\x02\n" +
	"\x0eControlMessage\x12&\n" +
	"\x05hello\x18\x01 \x01(\v2\x0e.entropy.HelloH\x00R\x05hello\x12<\n" +
	"\rconfig_update\x18\x02 \x01(\v2\x15.entropy.ConfigUpdateH\x00R\fconfigUpdate\x12<\n" +
	"\rhealth_report\x18\x03 \x01(\v2\x15.entropy.HealthReportH\x00R\fhealthReport\x12#\n" +
	"\x04ping\x18\x04 \x01(\v2\r.entropy.PingH\x00R\x04ping\x12#\n" +
	"\x04pong\x18\x05 \x01(\v2\r.entropy.PongH\x00R\x04pongB\t\n" +
	"\apayload*B\n" +
	"\fChecksumAlgo\x12\x1d\n" +
	"\x19CHECKSUM_ALGO_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fCHECKSUM_SHA256\x10\x01*F\n" +
	"\rSignatureAlgo\x12\x1e\n" +
	"\x1aSIGNATURE_ALGO_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11SIGNATURE_ED25519\x10\x01*9\n" +
	"\vCompression\x12\x14\n" +
	"\x10COMPRESSION_NONE\x10\x00\x12\x14\n" +
	"\x10COMPRESSION_ZSTD\x10\x012\xd5\x01\n" +
	"\rEntropyStream\x128\n" +
	"\rStreamEntropy\x12\x15.entropy.EntropyBatch\x1a\f.entropy.Ack(\x010\x01\x12I\n" +
	"\x10SubscribeBatches\x12\x1c.entropy.SubscriptionRequest\x1a\x15.entropy.EntropyBatch0\x01\x12?\n" +
	"\aControl\x12\x17.entropy.ControlMessage\x1a\x17.entropy.ControlMessage(\x010\x01B\x1cZ\x1aentropy-tdc-gateway/pkg/pbb\x06proto3"

var (
	file_api_proto_v1_entropy_proto_rawDescOnce sync.Once
	file_api_proto_v1_entropy_proto_rawDescData []byte
)

func file_api_proto_v1_entropy_proto_rawDescGZIP() []byte {
	file_api_proto_v1_entropy_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_entropy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_entropy_proto_rawDesc), len(file_api_proto_v1_entropy_proto_rawDesc)))
	})
	return file_api_proto_v1_entropy_proto_rawDescData
}

var file_api_proto_v1_entropy_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_proto_v1_entropy_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_proto_v1_entropy_proto_goTypes = []any{
	(ChecksumAlgo)(0),           // 0: entropy.ChecksumAlgo
	(SignatureAlgo)(0),          // 1: entropy.SignatureAlgo
	(Compression)(0),            // 2: entropy.Compression
	(*WhiteningStats)(nil),      // 3: entropy.WhiteningStats
	(*TestSummary)(nil),         // 4: entropy.TestSummary
	(*KvMeta)(nil),              // 5: entropy.KvMeta
	(*SubscriptionRequest)(nil), // 6: entropy.SubscriptionRequest
	(*EntropyBatch)(nil),        // 7: entropy.EntropyBatch
	(*TDCEvent)(nil),            // 8: entropy.TDCEvent
	(*EdgeMetrics)(nil),         // 9: entropy.EdgeMetrics
	(*Ack)(nil),                 // 10: entropy.Ack
	(*ConfigUpdate)(nil),        // 11: entropy.ConfigUpdate
	(*HealthReport)(nil),        // 12: entropy.HealthReport
	(*Nack)(nil),                // 13: entropy.Nack
	(*Ping)(nil),                // 14: entropy.Ping
	(*Pong)(nil),                // 15: entropy.Pong
	(*Hello)(nil),               // 16: entropy.Hello
	(*ControlMessage)(nil),      // 17: entropy.ControlMessage
	nil,                         // 18: entropy.KvMeta.LabelsEntry
}
var file_api_proto_v1_entropy_proto_depIdxs = []int32{
	18, // 0: entropy.KvMeta.labels:type_name -> entropy.KvMeta.LabelsEntry
	8,  // 1: entropy.EntropyBatch.events:type_name -> entropy.TDCEvent
	9,  // 2: entropy.EntropyBatch.metrics:type_name -> entropy.EdgeMetrics
	0,  // 3: entropy.EntropyBatch.checksum_algo:type_name -> entropy.ChecksumAlgo
	1,  // 4: entropy.EntropyBatch.signature_algo:type_name -> entropy.SignatureAlgo
	2,  // 5: entropy.EntropyBatch.compression:type_name -> entropy.Compression
	3,  // 6: entropy.EntropyBatch.whitening:type_name -> entropy.WhiteningStats
	4,  // 7: entropy.EntropyBatch.tests:type_name -> entropy.TestSummary
	5,  // 8: entropy.EntropyBatch.meta:type_name -> entropy.KvMeta
	5,  // 9: entropy.Hello.meta:type_name -> entropy.KvMeta
	16, // 10: entropy.ControlMessage.hello:type_name -> entropy.Hello
	11, // 11: entropy.ControlMessage.config_update:type_name -> entropy.ConfigUpdate
	12, // 12: entropy.ControlMessage.health_report:type_name -> entropy.HealthReport
	14, // 13: entropy.ControlMessage.ping:type_name -> entropy.Ping
	15, // 14: entropy.ControlMessage.pong:type_name -> entropy.Pong
	7,  // 15: entropy.EntropyStream.StreamEntropy:input_type -> entropy.EntropyBatch
	6,  // 16: entropy.EntropyStream.SubscribeBatches:input_type -> entropy.SubscriptionRequest
	17, // 17: entropy.EntropyStream.Control:input_type -> entropy.ControlMessage
	10, // 18: entropy.EntropyStream.StreamEntropy:output_type -> entropy.Ack
	7,  // 19: entropy.EntropyStream.SubscribeBatches:output_type -> entropy.EntropyBatch
	17, // 20: entropy.EntropyStream.Control:output_type -> entropy.ControlMessage
	18, // [18:21] is the sub-list for method output_type
	15, // [15:18] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_api_proto_v1_entropy_proto_init() }
func file_api_proto_v1_entropy_proto_init() {
	if File_api_proto_v1_entropy_proto != nil {
		return
	}
	file_api_proto_v1_entropy_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_proto_v1_entropy_proto_msgTypes[4].OneofWrappers = []any{}
	file_api_proto_v1_entropy_proto_msgTypes[5].OneofWrappers = []any{}
	file_api_proto_v1_entropy_proto_msgTypes[6].OneofWrappers = []any{}
	file_api_proto_v1_entropy_proto_msgTypes[7].OneofWrappers = []any{}
	file_api_proto_v1_entropy_proto_msgTypes[8].OneofWrappers = []any{}
	file_api_proto_v1_entropy_proto_msgTypes[14].OneofWrappers = []any{
		(*ControlMessage_Hello)(nil),
		(*ControlMessage_ConfigUpdate)(nil),
		(*ControlMessage_HealthReport)(nil),
		(*ControlMessage_Ping)(nil),
		(*ControlMessage_Pong)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_entropy_proto_rawDesc), len(file_api_proto_v1_entropy_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_entropy_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_entropy_proto_depIdxs,
		EnumInfos:         file_api_proto_v1_entropy_proto_enumTypes,
		MessageInfos:      file_api_proto_v1_entropy_proto_msgTypes,
	}.Build()
	File_api_proto_v1_entropy_proto = out.File
	file_api_proto_v1_entropy_proto_goTypes = nil
	file_api_proto_v1_entropy_proto_depIdxs = nil
}
