// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.5
// source: api/proto/v1/entropy.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EntropyStream_StreamEntropy_FullMethodName    = "/entropy.EntropyStream/StreamEntropy"
	EntropyStream_SubscribeBatches_FullMethodName = "/entropy.EntropyStream/SubscribeBatches"
	EntropyStream_Control_FullMethodName          = "/entropy.EntropyStream/Control"
)

// EntropyStreamClient is the client API for EntropyStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EntropyStream defines the gRPC service for entropy data exchange between
// edge gateways and the cloud processor backend.
type EntropyStreamClient interface {
	// StreamEntropy opens a bidirectional stream for transmitting entropy batches
	// from the edge gateway to the cloud and receiving acknowledgments in return.
	StreamEntropy(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EntropyBatch, Ack], error)
	// SubscribeBatches opens a server-to-client stream that broadcasts received
	// entropy batches to subscribing downstream consumers.
	SubscribeBatches(ctx context.Context, in *SubscriptionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EntropyBatch], error)
	// Control opens a bidirectional stream for exchanging control plane messages
	// such as configuration updates, health reports, and keepalive pings.
	Control(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ControlMessage, ControlMessage], error)
}

type entropyStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewEntropyStreamClient(cc grpc.ClientConnInterface) EntropyStreamClient {
	return &entropyStreamClient{cc}
}

func (c *entropyStreamClient) StreamEntropy(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EntropyBatch, Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EntropyStream_ServiceDesc.Streams[0], EntropyStream_StreamEntropy_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EntropyBatch, Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EntropyStream_StreamEntropyClient = grpc.BidiStreamingClient[EntropyBatch, Ack]

func (c *entropyStreamClient) SubscribeBatches(ctx context.Context, in *SubscriptionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EntropyBatch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EntropyStream_ServiceDesc.Streams[1], EntropyStream_SubscribeBatches_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscriptionRequest, EntropyBatch]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EntropyStream_SubscribeBatchesClient = grpc.ServerStreamingClient[EntropyBatch]

func (c *entropyStreamClient) Control(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ControlMessage, ControlMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EntropyStream_ServiceDesc.Streams[2], EntropyStream_Control_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ControlMessage, ControlMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EntropyStream_ControlClient = grpc.BidiStreamingClient[ControlMessage, ControlMessage]

// EntropyStreamServer is the server API for EntropyStream service.
// All implementations must embed UnimplementedEntropyStreamServer
// for forward compatibility.
//
// EntropyStream defines the gRPC service for entropy data exchange between
// edge gateways and the cloud processor backend.
type EntropyStreamServer interface {
	// StreamEntropy opens a bidirectional stream for transmitting entropy batches
	// from the edge gateway to the cloud and receiving acknowledgments in return.
	StreamEntropy(grpc.BidiStreamingServer[EntropyBatch, Ack]) error
	// SubscribeBatches opens a server-to-client stream that broadcasts received
	// entropy batches to subscribing downstream consumers.
	SubscribeBatches(*SubscriptionRequest, grpc.ServerStreamingServer[EntropyBatch]) error
	// Control opens a bidirectional stream for exchanging control plane messages
	// such as configuration updates, health reports, and keepalive pings.
	Control(grpc.BidiStreamingServer[ControlMessage, ControlMessage]) error
	mustEmbedUnimplementedEntropyStreamServer()
}

// UnimplementedEntropyStreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEntropyStreamServer struct{}

func (UnimplementedEntropyStreamServer) StreamEntropy(grpc.BidiStreamingServer[EntropyBatch, Ack]) error {
	return status.Error(codes.Unimplemented, "method StreamEntropy not implemented")
}
func (UnimplementedEntropyStreamServer) SubscribeBatches(*SubscriptionRequest, grpc.ServerStreamingServer[EntropyBatch]) error {
	return status.Error(codes.Unimplemented, "method SubscribeBatches not implemented")
}
func (UnimplementedEntropyStreamServer) Control(grpc.BidiStreamingServer[ControlMessage, ControlMessage]) error {
	return status.Error(codes.Unimplemented, "method Control not implemented")
}
func (UnimplementedEntropyStreamServer) mustEmbedUnimplementedEntropyStreamServer() {}
func (UnimplementedEntropyStreamServer) testEmbeddedByValue()                       {}

// UnsafeEntropyStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EntropyStreamServer will
// result in compilation errors.
type UnsafeEntropyStreamServer interface {
	mustEmbedUnimplementedEntropyStreamServer()
}

func RegisterEntropyStreamServer(s grpc.ServiceRegistrar, srv EntropyStreamServer) {
	// If the following call panics, it indicates UnimplementedEntropyStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EntropyStream_ServiceDesc, srv)
}

func _EntropyStream_StreamEntropy_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EntropyStreamServer).StreamEntropy(&grpc.GenericServerStream[EntropyBatch, Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EntropyStream_StreamEntropyServer = grpc.BidiStreamingServer[EntropyBatch, Ack]

func _EntropyStream_SubscribeBatches_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscriptionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EntropyStreamServer).SubscribeBatches(m, &grpc.GenericServerStream[SubscriptionRequest, EntropyBatch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EntropyStream_SubscribeBatchesServer = grpc.ServerStreamingServer[EntropyBatch]

func _EntropyStream_Control_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EntropyStreamServer).Control(&grpc.GenericServerStream[ControlMessage, ControlMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EntropyStream_ControlServer = grpc.BidiStreamingServer[ControlMessage, ControlMessage]

// EntropyStream_ServiceDesc is the grpc.ServiceDesc for EntropyStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EntropyStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "entropy.EntropyStream",
	HandlerType: (*EntropyStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEntropy",
			Handler:       _EntropyStream_StreamEntropy_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SubscribeBatches",
			Handler:       _EntropyStream_SubscribeBatches_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Control",
			Handler:       _EntropyStream_Control_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/v1/entropy.proto",
}
